language: go
go:
  - 1.x
env:
  - TEST_SUITE=tests
  - TEST_SUITE=linter
install:
  - # Prevent default install action "go get -t -v ./...".
script:
  - make ci
after_success:
  - make cover
matrix:
  allow_failures:
    - go: master
