language: go

go:
  - 1.13.x
  - master

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - arm64

matrix:
  fast_finish: true
  allow_failures:
    - go: master
  exclude:
    - os: windows
      go: master
    - os: windows
      arch: arm64
    - os: osx
      arch: arm64

install:
  - go get -d -v -t ./...

script:
  - go test -v -race ./...
